name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        submodules: true
    - name: Build C tests
      run: |
        make bin/ares_test
    - name: Run C tests
      run: |
        ./bin/ares_test
      